name: Cross-Compile CMake Project
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master, github_actions_ci ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
        include:
          - platform: linux/arm64
            label: linux_arm64
            arch: aarch64
            distro: ubuntu_latest
          - platform: linux/amd64
            label: linux_amd64
            arch: none
            distro: none
            base_image: amd64/ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: uraimo/run-on-arch-action@v2
        name: Run emulated commands
        # if: ${{ matrix.label }} == 'linux_arm64'
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          base_image: ${{ matrix.base_image }}
          run: |
            docker buildx build --file "Dockerfile.${{ matrix.label }}" --tag "${{ matrix.label }}:$(date +%s)" .
      - name: Deploy final binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: contract_csharp_plugin_{{ matrix.label }}
          path: opt/bin/contract_csharp_plugin
