name: Build Multi-arch Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 14783538_improve_cs_generator]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: [linux/amd64, linux/arm64, or darwin/amd64]

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --tag aelf.io/aeshanw/multi-arch-gha:latest .