name: compile_and_test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 14783538_improve_cs_generator]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build_and_test:
    name: Build & test CMAKE on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [ g++-10 ]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            target: Linux
          - os: macos-latest
            compiler: g++-10
            target: Macos
          - os: windows-latest
            compiler: cl
            target: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Run the projects cmake setup.
        run: cmake .
      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Compile a release build of contract-plugin
        run: make